# startup_input is how you configure the UI.  It's literally just a set of keys
# that will be passed into the UI as if you typed them.  This key will turn
# off the db logs:
# startup_input: "!"

# log_dir is where persistent logs are written to.
# log_dir: /tmp/devcluster-logs

# stages is the configuration of the whole cluster.  Each stage must be
# completed before moving to the next stage, so order matters.  This example
# assumes that devcluster.py is responsible for the database, but if you wanted
# to run it externally then you could just remove the "db" stage here.
stages:

  # db is predefined type of stage specific to how determined runs the
  # database.
  - db:
      # port: 5432
      # db_name: determined
      # password: postgres
      # container_name: determined_db

      # data_dir is where the persistent files will be saved to.
      data_dir: ~/.postgres

  # master is a predefined type of stage for to how determined runs the master.
  - master:
      # pre is a set of precommands to be run before starting the master.
      # In this case those commands are just a pair of make targets, specified
      # as shell commands.
      pre:
        - sh: make -C master build
        - sh: make -C tools prep-root
      # config_file is the most important config detail for the master stage.
      # It is literally just master.yaml.
      config_file:
        db:
          host: localhost
          port: 5432
          password: postgres
          user: postgres
          name: determined
        checkpoint_storage:
          type: shared_fs
          host_path: /tmp
          storage_path: determined-cp
        log:
          level: debug
        # This is important: we have to use the symbolic links in the
        # tools/build directory to run properly.
        root: tools/build

  - agent:
      pre:
        - sh: make -C agent build
      config_file:
        # NOTE: you need to put in an address for the master which is
        # resolvable from BOTH inside and outside docker.  I have been using my
        # laptop's external IP address, 192.168.0.4, but you may be able to
        # put you computer's hostname here.  host.docker.internal will not work.
        master_host: MY_IP_ADDR
        master_port: 8080
